### PR TITLE
add a bit more of drama to the readme

### PR DESCRIPTION
**Pull request by k0shk0sh**
to be fair for everyone

### CODE REVIEW

**Comment by thermatk** [comment]
I have a better suggestion, let's write a movie script out of it and sell it for a million bucks.
The money collected will let this fork use pro features forever

**Comment by k0shk0sh** [comment]
yes, please, then we could create a series out of it & create as many episodes as we want to make it more excited to people to watch. what do you say?

**Comment by thermatk** [comment]
default

**Comment by thermatk** [comment]
default
the right version

**Comment by k0shk0sh** [comment]
Git Wars had be perfect tho.

**Comment by k0shk0sh** [comment]
that's also fine :D ... 

I do expect you to make some changes to the readme tho, its unfair. 

Don't make ask for toooo many things. lets make life simple.

**Comment by thermatk** [comment]
default
which changes?

**Comment by k0shk0sh** [comment]
the dramatic stuff, make it less dramatic or accept this PR :D so to be fair for everyone.

**Comment by thermatk** [comment]
Added, in different less dramatic English if I may

**Pull request closed without merging**
